### ISSUE TITLE
Zone Control

### ISSUE THREAD

**Issue by Wob76** [lennyby93/node-mmcontrol#2]
Hi,

This is not an issue, but I wasn't sure how else to ask these questions.

First off, excuse a stupid question, but how are you utilising this, is it a plugin for an automation system or just used in a custom setup?

Also is it capable of controlling the zones? I didn't see mention of that in your readme.

I have a relatively new ducted system (PEA-RP140GAA) and I am finding that some of the rooms get too hot\cold when compared to the common area, mostly concerned about my kids rooms. What i am hoping to do is get some wifi sensor tags (like these http://wirelesstag.net/) and have them then in the zones and feed back, via some kind of automation system, preferably open source, or even IFTTT or stringify, to have it turn the zone on or off based some temperature settings.

I did find this thread (https://www.domoticz.com/forum/viewtopic.php?t=7496&start=40) but that is using the European version of melview, your project seems to be the only thing I can find with Australian support.

Thanks for your advice.
Wob

**Comment by lennyby93** [comment]
This is just a library that can be used by others.  I use it for my own setup (together with a bunch of other things). 

I don't have access to a systems with zone control so can't really implement it. 

My own system also used to suffer from the too hot/cold problem (I have a single zone system). The solution turned out to be quite simple - manually adjust the dampeners (from inside the attic) on every pipe to every room, the installers took some wild guesses with their settings and got it quite wrong.

**Comment by Wob76** [comment]
Hi, 

Thanks for the advice, I don't have any java skills so this is in the too hard basket for me, but I might have a friend have a look for me.

I'll just up in the roof and see if I can work out how to adjust the dampeners, might be an easier solution :).

Wob
